// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6333.DeepSpace.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc6333.DeepSpace.Robot;

/**
 * This command moves all arms until the switchs are closed
 * once all switches are closed it resets the encoders
 */
public class GotoStartPosition extends Command {

    
    public GotoStartPosition() {
        
        requires(Robot.shoulder_sub);

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        setInterruptible(true);
        

        Robot.shoulder_sub.setSetpoint(-484.0);
        Robot.fingers_sub.enable();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {

     
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if (Math.abs(-484-Robot.shoulder_sub.getShoulderEncoderCount())<50) {
            Robot.shoulder_sub.disable();
            return true;
        
        } else if (timeSinceInitialized() > 2.0) {
            return true;
        }
        else{
            return false;
        }
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.shoulder_sub.disable();

        System.out.print("Completed GotoStartPosition Command\n");
    }


    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
