// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6333.DeepSpace.commands;
import org.usfirst.frc6333.DeepSpace.Robot;

import edu.wpi.first.wpilibj.command.Command;
//import org.usfirst.frc6333.DeepSpace.Robot;

/**
 * This grabs the ball assuming it is set
 */
public class GrabBall extends Command {

    private int FingerSetpoint = 197000;

    public GrabBall() {

    
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {

        Robot.fingers_sub.setSetpoint(FingerSetpoint);
        Robot.fingers_sub.enable();

    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        
        if (Math.abs(FingerSetpoint-Robot.fingers_sub.getEncoder())<20000) {
            return true;
        } else return false;

    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.fingers_sub.disable();
        System.out.print("Completed GetBall Command\n");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
