// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6333.DeepSpace.commands;
import org.usfirst.frc6333.DeepSpace.Robot;
//import org.usfirst.frc6333.DeepSpace.OI;
import edu.wpi.first.wpilibj.command.Command;
//import org.usfirst.frc6333.DeepSpace.Robot;

/**
 * This command will check the state of the Ball/Hatch Button 
 * and either setup to place a ball in the high level of the rocket
 * or setup to place a hatch in the high level of the rocket.
 */
public class ReadIRSensor extends Command {


    public ReadIRSensor() {

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        Robot.DriveTrain_sub.distSensorAverage = Robot.DriveTrain_sub.getDistSensorAverage(Robot.DriveTrain_sub.leftIR.getValue());
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
      return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
