// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6333.DeepSpace.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6333.DeepSpace.Robot;

/**
 * This command moves the arm with wheel attached to lower the back of the robot down.
 * The command will check the state of the PlatformLevel button in order to determine 
 * how far to move the arm.
 */
public class WheelUp extends Command {

    public WheelUp() {

        requires(Robot.shoulder_sub);

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        Robot.shoulder_sub.moveShoulder(-0.6);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        /*if(!Robot.operatorInterface.shoulderDownButton.get()){
            return true;
        }
        
        else {
            return false;
        }*/
        return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.shoulder_sub.stopShoulder();
        if (!Robot.shoulder_sub.getShoulderStop()) {
            Robot.shoulder_sub.ResetShoulder();
        }
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
